---
- name: Run repo-setup
  ansible.builtin.command:
    cmd: >-
      {{ cifmw_repo_setup_basedir }}/venv/bin/repo-setup
      {{ cifmw_repo_setup_promotion }}
      -d {{ cifmw_repo_setup_os_release }}{{ cifmw_repo_setup_dist_major_version }}
      -b {{ cifmw_repo_setup_branch }}
      -o {{ cifmw_repo_setup_basedir }}/artifacts/repositories
